version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: dev
    volumes:
      - ./src:/var/www/html
      - ./docker/app/php/app.ini:/etc/php.d/app.ini
    environment:
      - APP_ENV=local
    ports:
      - 31180:80
    depends_on:
      - db
    init: true

  db:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - 33306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Tokyo
