version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: dev
    volumes:
      - ./src:/var/www/html
      - ./docker/app/php/app.ini:/etc/php.d/app.ini
    environment:
      - APP_ENV=local
    ports:
      - 31180:80
    init: true
